# Generated by Django 3.1.3 on 2020-11-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_hospitals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospitals',
            new_name='Hospital',
        ),
    ]
