# Generated by Django 3.1.3 on 2020-11-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20201109_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Locality',
            field=models.CharField(default=models.TextField(), max_length=25),
        ),
    ]
