# Generated by Django 3.1.3 on 2020-11-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_hospital_locality'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Beds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='MRI_Machine',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital',
            name='Oxygen_Cylinder',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='Locality',
            field=models.CharField(default=models.TextField(), max_length=50),
        ),
    ]
